### ISSUE TITLE
can not create virtualenv in st2-docker

### ISSUE THREAD

**Issue by vaibhavkumar049** [StackStorm-Exchange/stackstorm-git#12]
so I am running git in my st2-docker, but getting this error

The virtual environment (/opt/stackstorm/virtualenvs/git) for pack "git" does not exist. Normally this is
created when you install a pack using "st2 pack install". If you installed your pack by some other
means, you can create a new virtual environment using the command:
"st2 run packs.setup_virtualenv packs=git"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/container/process_container.py", line 283, in _run_all_sensors
    self._spawn_sensor_process(sensor=sensor_obj)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2reactor/container/process_container.py", line 309, in _spawn_sensor_process
    raise Exception(msg)
Exception:
The virtual environment (/opt/stackstorm/virtualenvs/git) for pack "git" does not exist. Normally this is
created when you install a pack using "st2 pack install". If you installed your pack by some other
means, you can create a new virtual environment using the command:
"st2 run packs.setup_virtualenv packs=git"

after even running "st2 run packs.setup_virtualenv packs=git" command can't find any file inside virtualenvs dir.

**Comment by peter-bartyik** [comment]
the virtualenv volume is not mounted in the client container. you'll need to involve the code from the sensor or action runner container
