### ISSUE TITLE
unable to run git.clone pack behind a proxy

### ISSUE THREAD

**Issue by sogloarcadius** [StackStorm-Exchange/stackstorm-git#5]
unable to use git pack behind a proxy.

my VM do not have direct access to the internet but behind a proxy

I set the proxy config on the host (export http_proxy and export https_proxy) and in stackstorm config files (/etc/sysconfig/st2actionrunner, /etc/sysconfig/st2api)

https://docs.stackstorm.com/packs.html#installing-packs-from-behind-a-proxy.

I could instal my packs using the proxy but unable to run the git.clone action. 

{
  "127.0.0.1": {
    "succeeded": false,
    "failed": true,
    "return_code": 128,
    "stderr": "Cloning into '/tmp/test'...
fatal: unable to access 'https://gitlab.com/xxxxx.git/': Could not resolve host: gitlab.com",
    "stdout": ""
  }
}

Is there any way to set the proxy settings in git pack configuration (/opt/stackstorm/configs/git.yaml)

Can't find any information on it in the git repo

Regards

**Comment by LindsayHill** [comment]
When you run the `git.clone` command, under the covers all it is doing is SSH'ing to whichever host you specify, and running `git clone ...`. It will do this as the system_user - by default `stanley`.

On whichever host you are running the git clone as, set your git configuration for the stanley user to specify a proxy. See https://gist.github.com/evantoli/f8c23a37eb3558ab8765 as an example of configuring git.
